footprint: [[-0.4, -0.22], [-0.4, 0.22], [0.4, 0.22], [0.4, -0.22]]
footprint_padding: 0.01

robot_base_frame: robot1_tf/chassis
update_frequency: 2.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: robot1_tf/hokuyo, data_type: LaserScan, clearing: true, marking: true, topic: /mybot/laser/scan, inf_is_valid: true, min_obstacle_height: -0.2}

inflation_radius: 0.75
